//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDataGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datagame
    {
        public int Id { get; set; }
        public string NameGame { get; set; }
        public string TypeGame { get; set; }
        public string Description_Game { get; set; }
        public string url { get; set; }
    }
}
